sudo: required

dist: trusty

language: node_js

node_js:
  - "7"
  - "6"
  - "5"
  - "4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:vapory/vapory
  - sudo add-apt-repository -y ppa:vapory/vapory-dev
  - sudo apt-get update -qq
  - sudo apt-get install gvap -y -qq
  - yes | gvap --datadir ~/.vapory-10101 &
  - sleep 5
  - killall gvap
  - yes | gvap --datadir ~/.vapory-7 &
  - sleep 5
  - killall gvap
  - npm install -g npm

install:
  - npm install
  - npm install jshint

script:
  - npm run lint
  - travis_wait 60 istanbul cover -x **/lib/** ./node_modules/mocha/bin/_mocha test/*.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
